Completed object-manipulation-3.- Meet Patel
meetkpatel/c0821-code-solutions pull request #60
Opened 2021-09-12 12:31 UTC by meetkpatel

<img width="424" alt="Screen Shot 2021-09-12 at 5 02 17 AM" src="https://user-images.githubusercontent.com/39370528/132987690-a7d393a7-b20f-4af2-8ad8-e7f8eec12106.png">
<img width="430" alt="Screen Shot 2021-09-12 at 5 01 40 AM" src="https://user-images.githubusercontent.com/39370528/132987693-2b31723b-67dc-4fd8-bee4-b884d70d2882.png">

2021-09-14 18:53 UTC, codingcodymiller requested changes
Nice work! A couple notes to get you started:

2021-09-14 18:53 UTC, codingcodymiller commented on object-manipulation-3/main.js
> +}
This is a bit needlessly complex. Instead, you should make an array of the `suits` and an array of the `ranks` for the cards, and loop over both of them to generate a full deck.

2021-09-14 18:53 UTC, codingcodymiller commented on object-manipulation-3/main.js
> +shuffleDistribution();
Why twice?

2021-10-04 22:22 UTC, thebearingedge approved these changes

2021-10-04 22:25 UTC, merged